### ISSUE TITLE
[question] how to handle innate spellcasting

### ISSUE THREAD

**Issue by Zorgatone** [valentine195/fantasy-statblocks#139]
Is there any YAML attribute for innate spellcasting?
I know we have the spells field, but what if one creature has both?

As a reference see the [Drow Mage](https://5e.tools/bestiary.html#drow%20mage_mm,fbsr:mage)

**Comment by sigrunixia** [comment]
When dealing with data from 5etools, the information rarely lines up 1:1, which is why Handlebars Templates have become so popular in our TTRPG Community. :)

There is no current specific attribute for spell casting, but think of the currently listed block options as less about their namesakes and more about what they do.
- Group creates a group
- Traits Lets you list out a name and a description.
- A property lists out one specific thing. 
- Spell is like a trimmed down traits. 

And so on. 

So for the Drow Mage, who I imported from 5E Tools, everything imported and the Innate Spellcasting was listed as under the general Spellcasting. It's not as pretty though. In those cases, you may want to manually adjust it to use a trait field instead, or consider a custom template. See below. 

With custom templates, you can have the same "type" of field multiple times, be named separate things. For instance, in the Pathfinder 2E Statblock, we heavily utilize traits for nearly every field, because of the functionality allotted for it. Here is a copy of the 5e Template with a simple Traits field, given the innatespellcasting name.

<img width="548" alt="image" src="https://user-images.githubusercontent.com/68425372/217416852-ae2a03e0-1148-4992-82f4-14a264fc8054.png">

**Comment by Zorgatone** [comment]
Yeah I'm writing this in Italian on Obsidian, so I am typing it all, translated, instead of importing it in english from 5etools.

Also I opened this other issue that prevents me to translate the spellcasting field in a custom template: https://github.com/valentine195/obsidian-5e-statblocks/issues/138

**Comment by sigrunixia** [comment]
Closing as this was addressed in an update, and we'll handle anything further in #138.
